# Generated by Django 4.1.5 on 2023-04-13 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0002_alter_meal_cook_time_hours_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='name',
            field=models.CharField(max_length=60),
        ),
    ]
